# Generated by Django 4.2 on 2024-12-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images')),
                ('visibility', models.CharField(choices=[('Only me', 'only me'), ('Everyone', 'everyone')], default='Everyone', max_length=20)),
            ],
        ),
    ]
