# Generated by Django 4.2 on 2024-12-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('Only me', 'only me'), ('Everyone', 'everyone')], default='Everyone', max_length=20),
        ),
    ]
